version: '3.8'

services:
  app:
    image: meet-manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=db;Database=MeetManager;User Id=sa;Password=Password1;

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    ports:
      - "1434:1433"
    environment:
      - SA_PASSWORD=Password1
      - ACCEPT_EULA=Y
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
